
import { LocalityData } from "@/types/dashboard";
import { getSavedVectorData } from "./vectorService";

// Mock data for the dashboard (fallback if no saved data)
export const mockDashboardData: LocalityData[] = [
  {
    municipality: "Itabuna",
    locality: "Centro",
    cycle: "01",
    epidemiologicalWeek: "01",
    workModality: "LI",
    startDate: "2024-01-01",
    endDate: "2024-01-07",
    totalProperties: 120,
    inspections: 100,
    depositsEliminated: 15,
    depositsTreated: 8,
    supervisor: "Maria Silva",
    qt_residencias: 90,
    qt_comercio: 25,
    qt_terreno_baldio: 3,
    qt_pe: 0,
    qt_outros: 2,
    qt_total: 120,
    tratamento_focal: 80,
    tratamento_perifocal: 20,
    amostras_coletadas: 5,
    recusa: 8,
    fechadas: 10,
    recuperadas: 2,
    a1: 4,
    a2: 3,
    b: 2,
    c: 3,
    d1: 2,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 200,
    quantidade_depositos_tratados: 8,
    adulticida: "",
    quantidade_cargas: 0,
    total_tec_saude: 4,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Mangabinha",
    cycle: "01",
    epidemiologicalWeek: "01",
    workModality: "LI",
    startDate: "2024-01-01",
    endDate: "2024-01-07",
    totalProperties: 85,
    inspections: 70,
    depositsEliminated: 12,
    depositsTreated: 6,
    supervisor: "João Santos",
    qt_residencias: 75,
    qt_comercio: 8,
    qt_terreno_baldio: 2,
    qt_pe: 0,
    qt_outros: 0,
    qt_total: 85,
    tratamento_focal: 60,
    tratamento_perifocal: 10,
    amostras_coletadas: 3,
    recusa: 5,
    fechadas: 8,
    recuperadas: 2,
    a1: 3,
    a2: 4,
    b: 2,
    c: 2,
    d1: 1,
    d2: 0,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 150,
    quantidade_depositos_tratados: 6,
    adulticida: "",
    quantidade_cargas: 0,
    total_tec_saude: 3,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "São Caetano",
    cycle: "01",
    epidemiologicalWeek: "02",
    workModality: "LI",
    startDate: "2024-01-08",
    endDate: "2024-01-14",
    totalProperties: 95,
    inspections: 80,
    depositsEliminated: 10,
    depositsTreated: 5,
    supervisor: "Pedro Almeida",
    qt_residencias: 80,
    qt_comercio: 10,
    qt_terreno_baldio: 4,
    qt_pe: 0,
    qt_outros: 1,
    qt_total: 95,
    tratamento_focal: 70,
    tratamento_perifocal: 10,
    amostras_coletadas: 2,
    recusa: 6,
    fechadas: 8,
    recuperadas: 1,
    a1: 2,
    a2: 3,
    b: 1,
    c: 2,
    d1: 1,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 120,
    quantidade_depositos_tratados: 5,
    adulticida: "",
    quantidade_cargas: 0,
    total_tec_saude: 3,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Zizo",
    cycle: "01",
    epidemiologicalWeek: "02",
    workModality: "LI",
    startDate: "2024-01-08",
    endDate: "2024-01-14",
    totalProperties: 70,
    inspections: 60,
    depositsEliminated: 8,
    depositsTreated: 4,
    supervisor: "Ana Oliveira",
    qt_residencias: 65,
    qt_comercio: 5,
    qt_terreno_baldio: 0,
    qt_pe: 0,
    qt_outros: 0,
    qt_total: 70,
    tratamento_focal: 55,
    tratamento_perifocal: 5,
    amostras_coletadas: 1,
    recusa: 4,
    fechadas: 5,
    recuperadas: 1,
    a1: 2,
    a2: 2,
    b: 1,
    c: 1,
    d1: 1,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 100,
    quantidade_depositos_tratados: 4,
    adulticida: "",
    quantidade_cargas: 0,
    total_tec_saude: 2,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Centro",
    cycle: "02",
    epidemiologicalWeek: "05",
    workModality: "LI",
    startDate: "2024-01-29",
    endDate: "2024-02-04",
    totalProperties: 125,
    inspections: 110,
    depositsEliminated: 18,
    depositsTreated: 9,
    supervisor: "Maria Silva",
    qt_residencias: 95,
    qt_comercio: 25,
    qt_terreno_baldio: 3,
    qt_pe: 0,
    qt_outros: 2,
    qt_total: 125,
    tratamento_focal: 95,
    tratamento_perifocal: 15,
    amostras_coletadas: 6,
    recusa: 7,
    fechadas: 7,
    recuperadas: 1,
    a1: 5,
    a2: 4,
    b: 3,
    c: 3,
    d1: 2,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 220,
    quantidade_depositos_tratados: 9,
    adulticida: "",
    quantidade_cargas: 0,
    total_tec_saude: 4,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Mangabinha",
    cycle: "02",
    epidemiologicalWeek: "05",
    workModality: "LI",
    startDate: "2024-01-29",
    endDate: "2024-02-04",
    totalProperties: 90,
    inspections: 75,
    depositsEliminated: 14,
    depositsTreated: 7,
    supervisor: "João Santos",
    qt_residencias: 80,
    qt_comercio: 8,
    qt_terreno_baldio: 2,
    qt_pe: 0,
    qt_outros: 0,
    qt_total: 90,
    tratamento_focal: 65,
    tratamento_perifocal: 10,
    amostras_coletadas: 4,
    recusa: 6,
    fechadas: 8,
    recuperadas: 1,
    a1: 4,
    a2: 3,
    b: 3,
    c: 2,
    d1: 1,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 170,
    quantidade_depositos_tratados: 7,
    adulticida: "",
    quantidade_cargas: 0,
    total_tec_saude: 3,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Pontalzinho",
    cycle: "01",
    epidemiologicalWeek: "03",
    workModality: "PE",
    startDate: "2024-01-15",
    endDate: "2024-01-21",
    totalProperties: 110,
    inspections: 90,
    depositsEliminated: 20,
    depositsTreated: 12,
    supervisor: "Carlos Pereira",
    qt_residencias: 90,
    qt_comercio: 15,
    qt_terreno_baldio: 2,
    qt_pe: 3,
    qt_outros: 0,
    qt_total: 110,
    tratamento_focal: 75,
    tratamento_perifocal: 15,
    amostras_coletadas: 5,
    recusa: 8,
    fechadas: 10,
    recuperadas: 2,
    a1: 6,
    a2: 5,
    b: 4,
    c: 3,
    d1: 1,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 250,
    quantidade_depositos_tratados: 12,
    adulticida: "Fenitrothion",
    quantidade_cargas: 3,
    total_tec_saude: 5,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Nova Itabuna",
    cycle: "01",
    epidemiologicalWeek: "04",
    workModality: "PE",
    startDate: "2024-01-22",
    endDate: "2024-01-28",
    totalProperties: 100,
    inspections: 85,
    depositsEliminated: 17,
    depositsTreated: 10,
    supervisor: "Fernanda Costa",
    qt_residencias: 85,
    qt_comercio: 10,
    qt_terreno_baldio: 2,
    qt_pe: 3,
    qt_outros: 0,
    qt_total: 100,
    tratamento_focal: 70,
    tratamento_perifocal: 15,
    amostras_coletadas: 4,
    recusa: 7,
    fechadas: 7,
    recuperadas: 1,
    a1: 5,
    a2: 4,
    b: 3,
    c: 3,
    d1: 1,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 200,
    quantidade_depositos_tratados: 10,
    adulticida: "Fenitrothion",
    quantidade_cargas: 2,
    total_tec_saude: 4,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Pontalzinho",
    cycle: "02",
    epidemiologicalWeek: "10",
    workModality: "PE",
    startDate: "2024-03-04",
    endDate: "2024-03-10",
    totalProperties: 115,
    inspections: 95,
    depositsEliminated: 22,
    depositsTreated: 14,
    supervisor: "Carlos Pereira",
    qt_residencias: 95,
    qt_comercio: 15,
    qt_terreno_baldio: 2,
    qt_pe: 3,
    qt_outros: 0,
    qt_total: 115,
    tratamento_focal: 80,
    tratamento_perifocal: 15,
    amostras_coletadas: 6,
    recusa: 9,
    fechadas: 10,
    recuperadas: 1,
    a1: 7,
    a2: 6,
    b: 4,
    c: 3,
    d1: 1,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 280,
    quantidade_depositos_tratados: 14,
    adulticida: "Fenitrothion",
    quantidade_cargas: 4,
    total_tec_saude: 5,
    total_dias_trabalhados: 5
  },
  {
    municipality: "Itabuna",
    locality: "Nova Itabuna",
    cycle: "02",
    epidemiologicalWeek: "11",
    workModality: "PE",
    startDate: "2024-03-11",
    endDate: "2024-03-17",
    totalProperties: 105,
    inspections: 90,
    depositsEliminated: 19,
    depositsTreated: 11,
    supervisor: "Fernanda Costa",
    qt_residencias: 90,
    qt_comercio: 10,
    qt_terreno_baldio: 2,
    qt_pe: 3,
    qt_outros: 0,
    qt_total: 105,
    tratamento_focal: 75,
    tratamento_perifocal: 15,
    amostras_coletadas: 5,
    recusa: 8,
    fechadas: 6,
    recuperadas: 1,
    a1: 6,
    a2: 5,
    b: 3,
    c: 3,
    d1: 1,
    d2: 1,
    e: 0,
    larvicida: "Pyriproxifen",
    quantidade_larvicida: 220,
    quantidade_depositos_tratados: 11,
    adulticida: "Fenitrothion",
    quantidade_cargas: 3,
    total_tec_saude: 4,
    total_dias_trabalhados: 5
  }
];

// Function to fetch dashboard data
export const fetchDashboardData = async (year: string = "2024"): Promise<LocalityData[]> => {
  // Simulate API call with timeout
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  // Get data from localStorage first
  const savedData = getSavedVectorData();
  console.log("Fetched saved data:", savedData);
  
  // If there's saved data, use it
  if (savedData && savedData.length > 0) {
    console.log("Using saved data:", savedData);
    // Filter by year
    return savedData.filter(data => data.startDate.startsWith(year));
  }
  
  // If no saved data is available, use mock data
  console.log("Using mock data");
  return mockDashboardData.filter(data => data.startDate.startsWith(year));
};
