
import { FormData } from "@/types/vectorForm";
import { format } from 'date-fns';

export const processVectorData = async (formData: FormData) => {
  // Simulate API call with timeout
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  // Simulate creating vector data - in a real app, this would be done by an API
  const mockVectorData = {
    municipality: formData.municipality,
    locality: formData.locality,
    cycle: formData.cycle,
    epidemiologicalWeek: formData.epidemiologicalWeek,
    startDate: formData.startDate,
    endDate: formData.endDate,
    quantitativeData: {
      residencias: formData.qt_residencias,
      comercio: formData.qt_comercio,
      terrenoBaldio: formData.qt_terreno_baldio,
      pe: formData.qt_pe,
      outros: formData.qt_outros,
      total: formData.qt_total,
      tratamento_focal: formData.tratamento_focal,
      tratamento_perifocal: formData.tratamento_perifocal,
      inspecionados: formData.inspecionados,
      amostras_coletadas: formData.amostras_coletadas,
      recusa: formData.recusa,
      fechadas: formData.fechadas,
      recuperadas: formData.recuperadas
    },
    depositsData: {
      a1: formData.a1,
      a2: formData.a2,
      b: formData.b,
      c: formData.c,
      d1: formData.d1,
      d2: formData.d2,
      e: formData.e,
      depositos_eliminados: formData.depositos_eliminados
    },
    treatedDepositsData: {
      larvicida: formData.larvicida,
      quantidade_larvicida: formData.quantidade_larvicida,
      quantidade_depositos_tratados: formData.quantidade_depositos_tratados,
      adulticida: formData.adulticida,
      quantidade_cargas: formData.quantidade_cargas,
      total_tec_saude: formData.total_tec_saude,
      total_dias_trabalhados: formData.total_dias_trabalhados,
      nome_supervisor: formData.nome_supervisor
    }
  };
  
  // Simulate summary - in a real app, this would be generated by an API
  const mockSummary = `Resumo para ${formData.municipality}, ${formData.locality}, durante o ciclo ${formData.cycle} (semana epidemiológica ${formData.epidemiologicalWeek}). Período: ${formData.startDate ? format(formData.startDate, 'PP') : 'N/A'} a ${formData.endDate ? format(formData.endDate, 'PP') : 'N/A'}. Total de imóveis: ${formData.qt_total}. Depósitos eliminados: ${formData.depositos_eliminados || 0}. Depósitos tratados: ${formData.quantidade_depositos_tratados || 0}. Supervisor: ${formData.nome_supervisor || 'N/A'}.`;
  
  return { mockVectorData, mockSummary };
};
