
// List of localities used throughout the application
export const localities = [
  "Alemita",
  "Alto Maron", 
  "Antique",
  "Bananeira",
  "Banco Raso", 
  "California", 
  "Carlos Silva", 
  "Castalia", 
  "Centro",
  "Centro Comercial",
  "Conceicao",
  "Corbiniano Freire",
  "Daniel Gomes",
  "Fatima",
  "Fernando Gomes", 
  "Ferradas",
  "Fonseca", 
  "Goes Calmon", 
  "Horteiro",
  "Itamaraca",
  "Jacana",
  "Jardim Brasil",
  "Jardim Grapiuna",
  "Jardim Primavera",
  "Joao Soares",
  "Jorge Amado",
  "Lomanto",
  "Mangabinha",
  "Manoel Leão",
  "Maria Matos",
  "Maria Pinheiro",
  "Monte Cristo",
  "Mutuns",
  "N S das Gracas", 
  "Nova California",
  "Nova Esperança",
  "Nova Ferradas",
  "Nova Itabuna", 
  "Nova Fonseca", 
  "Novo Horizonte",
  "Novo S Caetano",
  "Parque Boa Vista",
  "Parque Verde",
  "Pedro Geronimo",
  "Pontalzinho",
  "Roca do Povo",
  "Santa Catarina",
  "Santa Clara",
  "Santa Ines",
  "Santo Antonio",
  "Sao Caetano",
  "Sao Judas",
  "Sao Lourenço",
  "Sao Pedro",
  "Sao Roque",
  "Sarinha",
  "Sinval Palmeira",
  "Taverolandia",
  "Urbis IV",
  "Vila Analia",
  "Vila Paloma",
  "Zildolandia",
  "Zizo"
];
